proc sql;
%if %sysfunc(exist(CASUSER.INFORMATION_HOUSEHOLDS)) %then %do;
    drop table CASUSER.INFORMATION_HOUSEHOLDS;
%end;
%if %sysfunc(exist(CASUSER.INFORMATION_HOUSEHOLDS,VIEW)) %then %do;
    drop view CASUSER.INFORMATION_HOUSEHOLDS;
%end;
quit;



FILENAME REFFILE DISK '/shared/home/francesco.feroldi01@icatt.it/casuser/DataFiles/informations_households.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=CASUSER.INFORMATION_HOUSEHOLDS;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=CASUSER.INFORMATION_HOUSEHOLDS; RUN;


