proc sql;
%if %sysfunc(exist(DATASETS.INFORMATION_HOUSEHOLDS)) %then %do;
    drop table DATASETS.INFORMATION_HOUSEHOLDS;
%end;
%if %sysfunc(exist(DATASETS.INFORMATION_HOUSEHOLDS,VIEW)) %then %do;
    drop view DATASETS.INFORMATION_HOUSEHOLDS;
%end;
quit;



FILENAME REFFILE DISK '/shared/home/francesco.feroldi01@icatt.it/casuser/DataFiles/informations_households.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=DATASETS.INFORMATION_HOUSEHOLDS;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=DATASETS.INFORMATION_HOUSEHOLDS; RUN;


